import { useState } from 'react';
import ProfessionalHeader from '../components/ProfessionalHeader.jsx';

const DEFAULT_EXERCISES=['Voador','Supino inclinado máquina','Supino reto','Puxada alta','Remada baixa máquina','Elevação lateral','Desenvolvimento máquina','Leg press','Cadeira extensora','Mesa flexora','Rosca Scott máquina','Tríceps máquina'];

export default function WorkoutsPage({theme,accent,setTheme,setAccent}){
 const [name,setName]=useState('Treino de hoje'); const [started,setStarted]=useState(false); const [items,setItems]=useState(DEFAULT_EXERCISES.slice(0,6).map((exercise,i)=>({exercise,sets:Array.from({length:i===3?3:3},()=>({kg:'',reps:'',done:false}))}))); const [rest,setRest]=useState(90);
 const update=(ei,si,key,value)=>setItems(a=>a.map((e,i)=>i!==ei?e:{...e,sets:e.sets.map((s,j)=>j!==si?s:{...s,[key]:value})}));
 const addSet=ei=>setItems(a=>a.map((e,i)=>i!==ei?e:{...e,sets:[...e.sets,{kg:'',reps:'',done:false}]}));
 const toggle= (ei,si)=>update(ei,si,'done',!items[ei].sets[si].done);
 const volume=items.reduce((t,e)=>t+e.sets.reduce((s,x)=>s+(Number(x.kg)||0)*(Number(x.reps)||0),0),0);
 return <div className="app workouts-screen"><ProfessionalHeader subtitle="Seu treino" theme={theme} accent={accent} setTheme={setTheme} setAccent={setAccent}/><main className="workouts-page"><div className="workouts-hero"><div><div className="eyebrow">ACADEMIA</div><h1>{started?'Treino em andamento':'Treinos'}</h1><p className="muted">Registre carga, repetições e evolução sem complicação.</p></div><div className="workout-actions">{!started?<button className="btn btn-primary" onClick={()=>setStarted(true)}>▶ Iniciar treino</button>:<button className="btn btn-primary" onClick={()=>setStarted(false)}>🏁 Finalizar</button>}</div></div>{started&&<section className="workout-toolbar"><input className="input" value={name} onChange={e=>setName(e.target.value)}/><label className="muted">Descanso <select className="input" value={rest} onChange={e=>setRest(Number(e.target.value))}><option value={60}>60s</option><option value={90}>90s</option><option value={120}>120s</option><option value={180}>180s</option></select></label></section>}<div className="workout-summary"><div><strong>{items.length}</strong><span>exercícios</span></div><div><strong>{items.reduce((n,e)=>n+e.sets.length,0)}</strong><span>séries</span></div><div><strong>{volume.toLocaleString('pt-BR')} kg</strong><span>volume</span></div></div>{items.map((item,ei)=><section className="workout-card" key={item.exercise}><div className="workout-card-head"><div><h2>{item.exercise}</h2><span className="muted">{item.sets.length} séries</span></div></div>{item.sets.map((set,si)=><div className={`workout-set ${set.done?'done':''}`} key={si}><span className="set-number">{si+1}</span><input className="input" inputMode="decimal" placeholder="kg" value={set.kg} onChange={e=>update(ei,si,'kg',e.target.value)}/><input className="input" inputMode="numeric" placeholder="reps" value={set.reps} onChange={e=>update(ei,si,'reps',e.target.value)}/><button className="set-check" onClick={()=>toggle(ei,si)}>{set.done?'✓':'○'}</button></div>)}<button className="btn btn-ghost add-set" onClick={()=>addSet(ei)}>+ Adicionar série</button></section>)}</main></div>
}
